### ISSUE TITLE
Issue with Scanning input directories for output

### ISSUE THREAD

**Issue by smks** [waud/waudbase64#1]
Lets say you have 5 directories with their own list of audio in a parent directory, and you need all audio contained in this parent. The command tool will only pick up the audio in the first sub directory. In the example it would only pick up **child_dir_1**

```
parent_dir
  child_dir_1
    sound_1.mp3
    sound_2.mp3
    sound_3.mp3
  child_dir_2
    sound_4.mp3
    sound_5.mp3
  child_dir_3
  child_dir_4
  child_dir_5
```

**Comment by adireddy** [comment]
Fixed it in v1.0.4. Can you try again?

**Comment by smks** [comment]
Okay sure! Checking..

**Comment by adireddy** [comment]
Installing the library globally fixed the issue `npm install -g waudbase64`
