### ISSUE TITLE
Optional `inputFolder`

### ISSUE THREAD

**Issue by 3vilguy** [waud/waudbase64#2]
Hello, I was trying to make base64 json where IDs are just filenames but I can't do this :/
Because `inputFolder` is required to run the script I can't just navigate to my assets folder and call `waudbase64`.
I can do `waudbase64 -i ./` but then in JSON I have IDs like:
`".//Sound_01.m4a"`
`".//Sound_01.m4a"`
etc...

Is there a easy way to bypass that?

**Comment by adireddy** [comment]
Try the new version waudbase64@1.0.6

input folder is optional now and defaults to `./`

added new option to ignore base path in asset ids, use

`waudbase64 --nb`

**Comment by 3vilguy** [comment]
Awesome! Thanks Adi :)
